/**
 * Dashboard Templates
 * Pre-configured dashboard templates using the existing widget schema
 * 
 * Each template contains:
 * - id: Unique identifier
 * - name: Display name
 * - description: What the template provides
 * - widgets: Array of WidgetInput objects that match the exact schema used throughout the app
 * 
 * Widget Schema Compliance:
 * - All widgets use WidgetInput type (omits id, lastUpdated, createdAt)
 * - Layout uses LayoutInput type (omits 'i' field - auto-generated by store)
 * - Config uses exact WidgetConfig discriminated union (card/table with fields, or chart with chartConfig)
 * - Fields use SelectedField interface with path, name, type, order, format
 */

import type { DashboardTemplate } from "../types/dashboard";
import type { WidgetInput } from "../types/widget";

/**
 * Live Stock Data Template
 * 
 * Displays current/live stock quote information in a card format
 * Shows real-time market data with comprehensive stock metrics
 * 
 * This template provides a comprehensive stock quote card with 9 key fields.
 * After selecting this template, users can edit it to:
 * - Connect to their own API endpoint
 * - Select which fields to display from their API data
 * - Customize field names and formatting
 * - Add or remove fields as needed
 */
export const liveStockDataTemplate: DashboardTemplate = {
  id: "live-stock-data",
  name: "Live Stock Quote",
  description: "Comprehensive stock quote card with 9 fields including Symbol, Open, High, Low, Price, Volume, Latest Trading Day, Previous Close, and Change. Edit to connect your API and customize fields.",
  category: "Finance",
  
  widgets: [
    {
      type: "card",
      title: "IBM",
      layout: {
        x: 0,
        y: 0,
        w: 4,
        h: 6,
        minW: 3,
        minH: 4,
      },
      config: {
        type: "card",
        apiEndpoint: "/data/stock-quote.json",
        refreshInterval: 30000,
        fields: [
          {
            path: "01. symbol",
            name: "Symbol",
            type: "string",
            order: 0,
          },
          {
            path: "02. open",
            name: "Open",
            type: "number",
            order: 1,
            format: {
              type: "number",
              decimals: 4,
            },
          },
          {
            path: "03. high",
            name: "High",
            type: "number",
            order: 2,
            format: {
              type: "number",
              decimals: 4,
            },
          },
          {
            path: "04. low",
            name: "Low",
            type: "number",
            order: 3,
            format: {
              type: "number",
              decimals: 4,
            },
          },
          {
            path: "05. price",
            name: "Price",
            type: "number",
            order: 4,
            format: {
              type: "number",
              decimals: 4,
            },
          },
          {
            path: "06. volume",
            name: "Volume",
            type: "number",
            order: 5,
            format: {
              type: "number",
              decimals: 0,
            },
          },
          {
            path: "07. latest trading day",
            name: "Latest Trading Day",
            type: "string",
            order: 6,
          },
          {
            path: "08. previous close",
            name: "Previous Close",
            type: "number",
            order: 7,
            format: {
              type: "number",
              decimals: 4,
            },
          },
          {
            path: "09. change",
            name: "Change",
            type: "number",
            order: 8,
            format: {
              type: "number",
              decimals: 4,
              showSign: true,
            },
          },
        ],
      },
      status: "idle",
    },
  ],
};

/**
 * Historical Stock Data Template
 * 
 * Displays daily historical stock data in a table format
 * Shows OHLCV (Open, High, Low, Close, Volume) data with dates
 * 
 * This template is designed for time series data from APIs like Alpha Vantage.
 * After selecting this template, users can edit it to:
 * - Connect to their own time series API endpoint
 * - Select which fields to display (Open, High, Low, Close, Volume, Date)
 * - Customize field names and formatting
 * - Filter date ranges as needed
 */
export const historicalStockDataTemplate: DashboardTemplate = {
  id: "historical-stock-data",
  name: "Historical Stock Data Table",
  description: "Display daily historical OHLCV stock data in a table format with dates. Perfect for time series analysis. Edit to connect your API.",
  category: "Finance",
  
  widgets: [
    {
      type: "table",
      title: "IBM",
      layout: {
        x: 0,
        y: 0,
        w: 12,
        h: 6,
        minW: 8,
        minH: 4,
      },
      config: {
        type: "table",
        apiEndpoint: "/data/stock-historical.json",
        refreshInterval: 300000,
        fields: [
          {
            path: "1. open",
            name: "OPEN",
            type: "number",
            order: 0,
            format: {
              type: "number",
              decimals: 4,
            },
          },
          {
            path: "date",
            name: "DATE",
            type: "string",
            order: 1,
          },
          {
            path: "2. high",
            name: "HIGH",
            type: "number",
            order: 2,
            format: {
              type: "number",
              decimals: 4,
            },
          },
          {
            path: "3. low",
            name: "LOW",
            type: "number",
            order: 3,
            format: {
              type: "number",
              decimals: 4,
            },
          },
          {
            path: "4. close",
            name: "CLOSE",
            type: "number",
            order: 4,
            format: {
              type: "number",
              decimals: 4,
            },
          },
          {
            path: "5. volume",
            name: "VOLUME",
            type: "number",
            order: 5,
            format: {
              type: "number",
              decimals: 0,
            },
          },
        ],
      },
      status: "idle",
    },
  ],
};

/**
 * All available dashboard templates
 * Export as array for easy iteration in UI
 */
export const dashboardTemplates: DashboardTemplate[] = [
  liveStockDataTemplate,
  historicalStockDataTemplate,
];

/**
 * Helper function to get template by ID
 */
export function getTemplateById(id: string): DashboardTemplate | undefined {
  return dashboardTemplates.find((template) => template.id === id);
}

/**
 * Helper function to get templates by category
 */
export function getTemplatesByCategory(category: string): DashboardTemplate[] {
  return dashboardTemplates.filter((template) => template.category === category);
}
